### ISSUE TITLE
Python AWS commands 

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosi-data-challenge-2#4]
I’ve been thinking about adding a cell on each Jupyter NB that downloads all the files needed to run the NB. I think it can be done with the awscli library (installed already by cosipy). I’ll look into that since it’s been a common problem reported by many people

**Comment by ckarwin** [comment]
That's a good idea. I think some of the notebooks already have this (e.g. the spectral fit and extended source fit NBs). Specifically, they have the wasabi terminal commands wrapped in an `os.system` command, but the right paths and files are there. Is this what you had in mind, or something else?

**Comment by ckarwin** [comment]
That's not a bad idea. Yeah, wasabi can be spotty sometimes.

**Comment by avalluvan** [comment]
A suggestion relevant to this discussion: could you add the following to the tutorial notebooks
1. the size of the file being retrieved as a comment - helps plan out time-consuming downloads vs those on the fly
2. an `if`-clause to avoid redownloading a file that already exists at the specified data path (unless manually overriden) - a mis-click can sometimes result in a ~20 min wait time

**Comment by ckarwin** [comment]
Thanks for the suggestions, @avalluvan. 

Yes, we can add the file size. 

Sure, the `if` statement can be included in the wasabi download wrapper function.

**Comment by israelmcmc** [comment]
I added the function here: https://github.com/cositools/cosipy/pull/141

@ckarwin Can you please review and merge?

**Comment by ckarwin** [comment]
The new utility function has been merged into the main branch. I'll wait until all the notebooks have been updated before closing this issue.

**Comment by israelmcmc** [comment]
Sounds good. Thanks, @ckarwin

**Comment by ckarwin** [comment]
This issue can be closed now. All notebooks have been updates.
