### ISSUE TITLE
Add conda and jupyter installation instructions.

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosi-data-challenge-2#5]
I'm thinking of adding an installation section here that includes the installation of conda and Jupyter. Libraries themselves do not typically include these instructions in their documentation because there are multiple ways the user might want to use them, and conda an jupyter nb are only some options. We can however leave the instruction in cosipy itself simple, and add step-by-step instructions here to setup an environment where you can run the data challenges.

**Comment by ckarwin** [comment]
Yes, that would be helpful. Maybe in the cosipy-intro directory, you can add another section after the intro that points users to the main cosipy documentation, but then also gives more detailed instructions for conda and Jupyter.
