### ISSUE TITLE
Information on the input data of the extragalactic sources

### ISSUE THREAD

**Issue by RebeccaRohde01** [cositools/cosi-data-challenge-2#9]
Hey!

I have two questions about the Extragalactic section of the Cosi Data Challenge 2.

For the input data of 3C279_low100 and 3C279_high100, the given value for the flux must be multiplied by 2. Does this also apply to the spectral data?

For 3C 273 it says that the baseline model can be found in Madsen et al 2015. Where do the input data of 3C 279 and 4C+21.35 come from?

Thank you very much!

**Comment by ckarwin** [comment]
Hello,

> For the input data of 3C279_low100 and 3C279_high100, the given value for the flux must be multiplied by 2. Does this also apply to the spectral data?

For the MEGAlib simulations, the normalization is set by the Flux keyword in the source file, whereas the spectrum just gives the shape. The factor of 2 that is mentioned in the spectrum files has already been applied in the source files (and thus in the simulations). If you wanted to just plot the spectrum from the given file at the same normalization level as the simulations, then yes, you would need to multiply by 2. 

> Where do the input data of 3C 279 and 4C+21.35 come from?

The input for 3C 279 is from the work here: https://ui.adsabs.harvard.edu/abs/2015ApJ...804...58Z/abstract

For 4C+21.35, the light curve is taken from the Fermi light curve repository, and the spectrum is extrapolated from the Fermi-LAT log parabola model from the 4FGL-DR3 (which is also the one used in the light curve repository). 

Hopefully this answers your questions, but please let me know if I need to clarify anything else.

**Comment by RebeccaRohde01** [comment]
Thank you, this helps me a lot!

**Comment by RebeccaRohde01** [comment]
Hello @ckarwin,
I have another question. I would like to plot the input data. So I wanted to ask from which 3 months exactly the data for 3C279 and 4C+21.35 were taken?
Thank you!
